### PR TITLE
bucketToIndexerLambda publishes to sqs and emitsIpfsEvent in parallel…

### LINKED ISSUE #15: bucket-to-indexer should send sqs+sns in parallel instead of in series (should save lambda $)
Motivation
* We noticed that deploying #13 increased lambda duration by ~100%. Not surprising, but let's see if this change lowers that by a meaningful amount.

Hypothesis:
* this change will lower avg lambda duration by 25%

### PR DESCRIPTION
**Pull request by gobengo**
… (try to reduce lambda duration)

Motivation:
* #15

### CODE REVIEW

**Comment by simone-sanfratello** [comment]
code is ok, but why do we use a lambda for sending multiple events? Can we send only tp SNS and then to other targets, including the SQS queue?

**Comment by francardoso93** [comment]
> code is ok, but why do we use a lambda for sending multiple events? Can we send only to SNS and then to other targets, including the SQS queue?

`publishToSQS` function could have a more meaningful name, like `emitIndexRequest`. As you can see, this is a different type of event than `emitIpfsEvent`, they are unrelated. 

For now we only have one lambda interested in `emitIndexRequest` (Indexer Lambda), so SQS queue does the job well, but if we introduce another component that wants to subscribe to that, then I agree 100% this should go to a different SNS topic (or the same and the subscriptions need to start filtering messages).

**Comment by gobengo** [comment]
> Can we send only tp SNS and then to other targets, including the SQS queue?

Yeah but it would take more than a couple hours to get there. We should decide whether and when to invest in that as a separate issue. @simone-sanfratello

**Review by alanshaw — APPROVED** [review]
Code change LGTM

**Comment by simone-sanfratello** [comment]
> > Can we send only tp SNS and then to other targets, including the SQS queue?
> 
> Yeah but it would take more than a couple hours to get there. We should decide whether and when to invest in that as a separate issue. @simone-sanfratello

We don't need to do that now, but let's keep in mind if we need to add more "stuff"

**Pull request merged**
